import mongoose from 'mongoose';

/** One answer to one question. `value` is boolean | number | string by type. */
const answerSchema = new mongoose.Schema(
  {
    questionId: { type: String, required: true, trim: true },
    // Mixed because yesNo -> boolean, number -> Number, singleChoice/text -> String.
    value: { type: mongoose.Schema.Types.Mixed, required: true },
  },
  { _id: false }
);

/**
 * A single school visit.
 *
 * The school and month details are copied onto the visit on purpose
 * (denormalised) so that listing visits and building the report are both
 * single-collection reads with no joins at query time.
 */
const visitSchema = new mongoose.Schema(
  {
    // Generated by the app per visit and replayed verbatim on every retry.
    clientId: { type: String, required: true, trim: true },

    userId: { type: String, required: true, trim: true, uppercase: true },
    udiseCode: { type: String, required: true, trim: true },

    // Copied from the school at save time. Lets GET /api/visits return a
    // school name without a lookup and lets the report group by block alone.
    schoolName: { type: String, required: true, trim: true },
    districtCode: { type: String, required: true, trim: true },
    blockCode: { type: String, required: true, trim: true },
    clusterCode: { type: String, required: true, trim: true },

    /** A real date, never a string. */
    visitedAt: { type: Date, required: true },

    // The IST calendar month of visitedAt, stored as numbers so that every
    // month filter and the report are plain equality matches with no
    // timezone arithmetic in the query.
    year: { type: Number, required: true },
    month: { type: Number, required: true, min: 1, max: 12 },

    answers: { type: [answerSchema], default: [] },
  },
  {
    timestamps: true,
    collection: 'visits',
    versionKey: false,
  }
);

// THE idempotency guarantee. The app may replay a visit any number of times
// (retry, app killed mid-sync, two syncs at once); a unique index makes a
// second row physically impossible, and the duplicate is caught as E11000.
visitSchema.index({ clientId: 1 }, { unique: true, name: 'clientId_unique' });

// GET /api/visits returns one user's visits newest first, with year/month as
// optional filters. userId leads because it is the only mandatory filter, so
// the same index serves both the unfiltered and the month-filtered case.
visitSchema.index({ userId: 1, year: 1, month: 1, visitedAt: -1 }, { name: 'user_timeline' });

// The report is always scoped to a month and then grouped by block, so the
// index leads with year/month. The same prefix also serves the district
// total, which filters year/month and then narrows to the district.
visitSchema.index(
  { year: 1, month: 1, blockCode: 1, districtCode: 1 },
  { name: 'report_scope' }
);

export const Visit = mongoose.model('Visit', visitSchema);
export default Visit;
